import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { Typography } from "@/components/ui/Typography";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export default function PrivacyPage() {
    return (
        <main className="bg-vb-dark min-h-screen selection:bg-vb-neon/30">
            <Navbar />
            <Section className="pt-32 pb-20">
                <Container>
                    <Typography variant="small" className="text-vb-neon uppercase tracking-widest mb-4 font-bold">Legal</Typography>
                    <Typography variant="h1" className="mb-8">Privacy Policy</Typography>
                    <div className="prose prose-invert prose-lg max-w-none space-y-8 text-vb-text/80">
                        <p className="lead border-l-4 border-vb-neon pl-6 italic">
                            Effective Date: {new Date().toLocaleDateString()}
                        </p>

                        <p>
                            VeeBran Consulting (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by VeeBran. This Privacy Policy applies to our website, and its associated subdomains (collectively, our &quot;Service&quot;). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                        </p>

                        <hr className="border-white/10" />

                        <h3>1. Definitions and Key Terms</h3>
                        <ul className="list-disc pl-6 space-y-2">
                            <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                            <li><strong>Company:</strong> when this policy mentions &quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our,&quot; it refers to VeeBran Consulting, responsible for your information under this Privacy Policy.</li>
                            <li><strong>Country:</strong> where VeeBran or the owners/founders of VeeBran are based, in this case is United States/India.</li>
                            <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the VeeBran Service to manage the relationships with your consumers or service users.</li>
                            <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit VeeBran and use the services.</li>
                            <li><strong>IP Address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                            <li><strong>Personnel:</strong> refers to those individuals who are employed by VeeBran or are under contract to perform a service on behalf of one of the parties.</li>
                            <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                        </ul>

                        <h3>2. Information We Collect</h3>
                        <p>We collect information regarding you when you visit our Website, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Name / Username</li>
                            <li>Phone Numbers</li>
                            <li>Email Addresses</li>
                            <li>Job Titles</li>
                            <li>Billing Addresses</li>
                        </ul>

                        <h3>3. How We Use Your Information</h3>
                        <p>Any of the information we collect from you may be used in one of the following ways:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
                            <li>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</li>
                            <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
                            <li>To process transactions</li>
                            <li>To send periodic emails</li>
                        </ul>

                        <h3>4. General Data Protection Regulation (GDPR)</h3>
                        <p>We may be processing Personal Data under the following conditions:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li><strong>Consent:</strong> You have given Your consent for processing Personal Data for one or more specific purposes.</li>
                            <li><strong>Performance of a contract:</strong> Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.</li>
                            <li><strong>Legal obligations:</strong> Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.</li>
                            <li><strong>Vital interests:</strong> Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.</li>
                            <li><strong>Public interests:</strong> Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.</li>
                            <li><strong>Legitimate interests:</strong> Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.</li>
                        </ul>
                        <p>In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.</p>

                        <h3>5. California Consumer Privacy Act (CCPA)</h3>
                        <p>Under the CCPA, among other rights, California consumers have the right to:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Request that a business that collects a consumer&apos;s personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</li>
                            <li>Request that a business delete any personal data about the consumer that a business has collected.</li>
                            <li>Request that a business that sells a consumer&apos;s personal data, not sell the consumer&apos;s personal data.</li>
                        </ul>
                        <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

                        <h3>6. Information Protection</h3>
                        <p>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file.</p>

                        <h3>7. Contact Us</h3>
                        <p>Don&apos;t hesitate to contact us if you have any questions providing:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Via Email: <a href="mailto:hello@veebran.com" className="text-vb-neon hover:underline">hello@veebran.com</a></li>
                            <li>Via this Link: <a href="/contact" className="text-vb-neon hover:underline">https://veebran.com/contact</a></li>
                        </ul>
                    </div>
                </Container>
            </Section>
            <Footer />
        </main>
    );
}
